export const COMPANY_POSTPRO_DEFAULTS = {
  enabled: true,
  vignetteEnabled: true,
  vignetteOffset: 0.1,
  vignetteDarkness: 1.14,
  colorEnabled: true,
  hue: -0.1,
  saturation: 0.25,
  bloom1Enabled: true,
  bloom1Intensity: 1.22,
  bloom1Threshold: 0.55,
  bloom1Smoothing: 0.08,
  bloom1Radius: 0.11,
  bloom1Levels: 1,
  bloom2Enabled: true,
  bloom2Intensity: 0.12,
  bloom2Threshold: 1,
  bloom2Smoothing: 0.12,
  bloom2Radius: 0.95,
  bloom2Levels: 7,
  godRaysEnabled: true,
  godRaysSamples: 40,
  godRaysDensity: 0.8,
  godRaysDecay: 0.9,
  godRaysWeight: 0.4,
  godRaysExposure: 0.04,
  godRaysClampMax: 1,
};

