/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hand.glb hand.jsx 
*/

import { useGLTF } from "@react-three/drei";

export default function Hand(props) {
  const { nodes, materials } = useGLTF("/models/hand.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.746, 0, 0]} rotation={[1.274, -0.709, -2.898]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials["Hands_Low_defaultMat1.001"]}
            position={[-0.55, -0.485, -0.137]}
            rotation={[2.731, -0.757, 0.751]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/hand.glb");
