/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/fort_island2.glb -o src/components/Island2.jsx -r public -k 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Island(props) {
  const { nodes, materials } = useGLTF("/models/fort_island2.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <group name="Circle" position={[0, 0, 0.072]}>
          <mesh
            name="Circle_2"
            geometry={nodes.Circle_2.geometry}
            material={materials.WATER_BLACK}
            position={[0, 0, -0.208]}
            scale={[1.117, 1.117, 1.031]}
          />
        </group>
        <group name="ground" scale={5.896}>
          <mesh
            name="ground_0"
            geometry={nodes.ground_0.geometry}
            material={materials.ground}
            position={[0, 0, -0.036]}
            scale={[1.117, 1.117, 1.031]}
          />
        </group>
        <group
          name="tree"
          position={[2.588, 2.484, 2.099]}
          rotation={[Math.PI, 0, -1.216]}
          scale={1.301}
        >
          <mesh
            name="tree_0"
            geometry={nodes.tree_0.geometry}
            material={materials.vang_tree_leaves}
          />
          <mesh
            name="tree_1"
            geometry={nodes.tree_1.geometry}
            material={materials.vang_tree_bark}
          />
        </group>
        <mesh
          name="floor_0"
          geometry={nodes.floor_0.geometry}
          material={materials.wall}
          position={[-3.949, -2.281, 0]}
        />
        <mesh
          name="foot_stones_0"
          geometry={nodes.foot_stones_0.geometry}
          material={materials.wall}
          position={[-3.949, -2.281, 0]}
        />
        <mesh
          name="foot_stones001_0"
          geometry={nodes.foot_stones001_0.geometry}
          material={materials.wall}
          position={[-3.949, 0.001, 0]}
        />
        <mesh
          name="grass_obj_01_01000_0"
          geometry={nodes.grass_obj_01_01000_0.geometry}
          material={materials.nord_grass}
          position={[-1.495, 2.407, 1.343]}
          rotation={[0, 0, 1.598]}
          scale={0.512}
        />
        <mesh
          name="grass_obj_01_01001_0"
          geometry={nodes.grass_obj_01_01001_0.geometry}
          material={materials.nord_grass}
          position={[-2.472, -1.036, 1.394]}
          rotation={[0, 0, -1.601]}
          scale={0.472}
        />
        <mesh
          name="grass_obj_01_01002_0"
          geometry={nodes.grass_obj_01_01002_0.geometry}
          material={materials.nord_grass}
          position={[3.494, 0.35, 1.343]}
          rotation={[0, 0, 1.598]}
          scale={0.989}
        />
        <mesh
          name="grass_obj_01_02000_0"
          geometry={nodes.grass_obj_01_02000_0.geometry}
          material={materials.nord_grass}
          position={[-2.834, 2.462, 1.386]}
          rotation={[0, 0, 0.377]}
          scale={0.643}
        />
        <mesh
          name="grass_obj_01_02001_0"
          geometry={nodes.grass_obj_01_02001_0.geometry}
          material={materials.nord_grass}
          position={[2.237, -2.191, 1.386]}
          rotation={[0, 0, 0.377]}
          scale={0.812}
        />
        <mesh
          name="grass_obj_02001_0"
          geometry={nodes.grass_obj_02001_0.geometry}
          material={materials.nord_grass}
          position={[0.315, 2.86, 1.374]}
          rotation={[0, 0, -0.144]}
          scale={0.655}
        />
        <mesh
          name="grass_obj_03_01001_0"
          geometry={nodes.grass_obj_03_01001_0.geometry}
          material={materials.nord_grass}
          position={[-2.58, 1.246, 1.371]}
          scale={0.713}
        />
        <mesh
          name="grass_obj_03_02000_0"
          geometry={nodes.grass_obj_03_02000_0.geometry}
          material={materials.nord_grass}
          position={[0.536, 3.556, 1.416]}
          rotation={[0, 0, -0.953]}
          scale={0.777}
        />
        <mesh
          name="grass_obj_03_02001_0"
          geometry={nodes.grass_obj_03_02001_0.geometry}
          material={materials.nord_grass}
          position={[-3.698, 0.438, 1.416]}
          rotation={[0, 0, 2.873]}
          scale={0.45}
        />
        <mesh
          name="grass_obj_03_02002_0"
          geometry={nodes.grass_obj_03_02002_0.geometry}
          material={materials.nord_grass}
          position={[-1.468, -3.129, 1.416]}
          scale={0.697}
        />
        <mesh
          name="grass_obj_03_02003_0"
          geometry={nodes.grass_obj_03_02003_0.geometry}
          material={materials.nord_grass}
          position={[4.394, 1.333, 0.315]}
          rotation={[0, 0, 1.705]}
          scale={0.697}
        />
        <mesh
          name="grass_obj_04_01001_0"
          geometry={nodes.grass_obj_04_01001_0.geometry}
          material={materials.nord_grass}
          position={[-1.839, -0.659, 1.455]}
          rotation={[0, 0, 1.515]}
          scale={0.551}
        />
        <mesh
          name="grass_obj_04_02000_0"
          geometry={nodes.grass_obj_04_02000_0.geometry}
          material={materials.nord_grass}
          position={[3.126, -0.318, 1.414]}
          rotation={[0, 0, 0.212]}
          scale={0.588}
        />
        <mesh
          name="grass_obj_04_02001_0"
          geometry={nodes.grass_obj_04_02001_0.geometry}
          material={materials.nord_grass}
          position={[-3.623, -0.103, 1.414]}
          rotation={[0, 0, 0.212]}
          scale={0.401}
        />
        <mesh
          name="grass_obj_04_02002_0"
          geometry={nodes.grass_obj_04_02002_0.geometry}
          material={materials.nord_grass}
          position={[1.356, 4.214, 0.2]}
          rotation={[0, 0, 2.477]}
          scale={0.647}
        />
        <mesh
          name="grass_obj_05_01000_0"
          geometry={nodes.grass_obj_05_01000_0.geometry}
          material={materials.nord_grass}
          position={[-1.415, -3.972, 0.177]}
          rotation={[3.141, -0.047, -1.175]}
          scale={-1.095}
        />
        <mesh
          name="grass_obj_05_01001_0"
          geometry={nodes.grass_obj_05_01001_0.geometry}
          material={materials.nord_grass}
          position={[-0.352, -3.461, 1.326]}
          rotation={[-0.048, -0.021, 1.261]}
          scale={1.095}
        />
        <mesh
          name="grass_obj_05_01002_0"
          geometry={nodes.grass_obj_05_01002_0.geometry}
          material={materials.nord_grass}
          position={[-2.464, -0.557, 1.383]}
          rotation={[0, 0, -1.475]}
          scale={0.581}
        />
        <mesh
          name="grass_obj_05_01003_0"
          geometry={nodes.grass_obj_05_01003_0.geometry}
          material={materials.nord_grass}
          position={[3.252, -1.415, 1.435]}
          rotation={[-0.008, 0.001, 2.675]}
          scale={0.95}
        />
        <mesh
          name="grass_obj_05_02000_0"
          geometry={nodes.grass_obj_05_02000_0.geometry}
          material={materials.nord_grass}
          position={[-3.191, 1.643, 1.37]}
          rotation={[0, 0, -0.516]}
          scale={0.686}
        />
        <mesh
          name="grass_obj_05_02001_0"
          geometry={nodes.grass_obj_05_02001_0.geometry}
          material={materials.nord_grass}
          position={[-3.028, 0.365, 1.42]}
          rotation={[0, 0, -0.082]}
          scale={0.731}
        />
        <mesh
          name="grass_obj_05_02002_0"
          geometry={nodes.grass_obj_05_02002_0.geometry}
          material={materials.nord_grass}
          position={[-0.333, 3.343, 1.37]}
          rotation={[0, 0, -0.724]}
          scale={0.915}
        />
        <mesh
          name="grass_obj_05_02003_0"
          geometry={nodes.grass_obj_05_02003_0.geometry}
          material={materials.nord_grass}
          position={[1.335, -3.028, 1.177]}
          rotation={[0, 0, -1.582]}
          scale={1.299}
        />
        <mesh
          name="grass_obj_05_02004_0"
          geometry={nodes.grass_obj_05_02004_0.geometry}
          material={materials.nord_grass}
          position={[-2.071, 2.483, 1.359]}
          rotation={[0, 0, 2.666]}
          scale={0.909}
        />
        <mesh
          name="grass_obj_05_02005_0"
          geometry={nodes.grass_obj_05_02005_0.geometry}
          material={materials.nord_grass}
          position={[1.851, 3.027, 2.186]}
          rotation={[0, 0, -0.724]}
          scale={0.82}
        />
        <mesh
          name="grass_obj_05_02006_0"
          geometry={nodes.grass_obj_05_02006_0.geometry}
          material={materials.nord_grass}
          position={[3.13, 1.799, 2.248]}
          rotation={[0, 0, 2.125]}
          scale={0.899}
        />
        <mesh
          name="grass_obj_05_02007_0"
          geometry={nodes.grass_obj_05_02007_0.geometry}
          material={materials.nord_grass}
          position={[4.429, 2.632, 0.126]}
          rotation={[0, 0, -3.049]}
          scale={0.82}
        />
        <mesh
          name="grass_obj_06_01000_0"
          geometry={nodes.grass_obj_06_01000_0.geometry}
          material={materials.nord_grass}
          position={[-1.139, 3.419, 1.452]}
          rotation={[0, 0, -0.791]}
          scale={0.51}
        />
        <mesh
          name="grass_obj_06_01001_0"
          geometry={nodes.grass_obj_06_01001_0.geometry}
          material={materials.nord_grass}
          position={[-3.633, -0.681, 1.452]}
          rotation={[0, 0, -0.791]}
          scale={0.51}
        />
        <mesh
          name="grass_obj_06_02001_0"
          geometry={nodes.grass_obj_06_02001_0.geometry}
          material={materials.nord_grass}
          position={[2.827, -1.186, 1.365]}
          scale={0.825}
        />
        <mesh
          name="grass_obj_07000_0"
          geometry={nodes.grass_obj_07000_0.geometry}
          material={materials.nord_grass}
          position={[3.039, 3.196, 2.346]}
          rotation={[0, 0, -2.413]}
          scale={0.933}
        />
        <mesh
          name="grass_obj_07001_0"
          geometry={nodes.grass_obj_07001_0.geometry}
          material={materials.nord_grass}
          position={[-3.3, -0.982, 1.414]}
          rotation={[0, 0, 0.497]}
          scale={0.804}
        />
        <mesh
          name="grass_obj_07002_0"
          geometry={nodes.grass_obj_07002_0.geometry}
          material={materials.nord_grass}
          position={[1.895, 1.66, 2.254]}
          rotation={[0, 0, 0.974]}
          scale={0.936}
        />
        <mesh
          name="grass_obj_07003_0"
          geometry={nodes.grass_obj_07003_0.geometry}
          material={materials.nord_grass}
          position={[-3.594, -3.345, 0.207]}
          rotation={[0, 0, -2.246]}
          scale={0.833}
        />
        <mesh
          name="grass_obj_07004_0"
          geometry={nodes.grass_obj_07004_0.geometry}
          material={materials.nord_grass}
          position={[-1.628, -4.216, 0.196]}
          rotation={[0.19, -0.009, -1.852]}
          scale={0.833}
        />
        <mesh
          name="grass_obj_07005_0"
          geometry={nodes.grass_obj_07005_0.geometry}
          material={materials.nord_grass}
          position={[-2.486, -4.298, 0.18]}
          rotation={[0.146, -0.064, 2.314]}
          scale={0.833}
        />
        <mesh
          name="grass_obj_07006_0"
          geometry={nodes.grass_obj_07006_0.geometry}
          material={materials.nord_grass}
          position={[-2.998, -4.072, 0.225]}
          rotation={[0.23, 0.012, 1.249]}
          scale={0.474}
        />
        <mesh
          name="grass_obj_07007_0"
          geometry={nodes.grass_obj_07007_0.geometry}
          material={materials.nord_grass}
          position={[4.391, -0.087, 0.177]}
          rotation={[0.025, 0.077, 1.588]}
          scale={1.149}
        />
        <mesh
          name="grass_obj_07008_0"
          geometry={nodes.grass_obj_07008_0.geometry}
          material={materials.nord_grass}
          position={[4.909, 0.706, 0.137]}
          rotation={[0.078, 0.037, -2.715]}
          scale={1.308}
        />
        <mesh
          name="grass_obj_07009_0"
          geometry={nodes.grass_obj_07009_0.geometry}
          material={materials.nord_grass}
          position={[4.848, 1.955, 0.158]}
          rotation={[-0.004, 0.076, -1.417]}
          scale={1.308}
        />
        <mesh
          name="grass_obj_07010_0"
          geometry={nodes.grass_obj_07010_0.geometry}
          material={materials.nord_grass}
          position={[0.156, 4.2, 0.201]}
          rotation={[-0.037, 0.006, -3.098]}
          scale={1.064}
        />
        <mesh
          name="grass_obj_07011_0"
          geometry={nodes.grass_obj_07011_0.geometry}
          material={materials.nord_grass}
          position={[-0.565, 4.27, 0.192]}
          rotation={[-0.086, -0.082, -1.51]}
          scale={1.064}
        />
        <mesh
          name="grass_obj_07012_0"
          geometry={nodes.grass_obj_07012_0.geometry}
          material={materials.nord_grass}
          position={[1.145, 4.452, 0.197]}
          rotation={[-0.143, 0.03, -1.657]}
          scale={1.064}
        />
        <mesh
          name="grass_obj_07013_0"
          geometry={nodes.grass_obj_07013_0.geometry}
          material={materials.nord_grass}
          position={[-4.126, -2.908, 0.052]}
          rotation={[0.026, -0.124, 2.2]}
          scale={1.024}
        />
        <mesh
          name="grass_obj_07014_0"
          geometry={nodes.grass_obj_07014_0.geometry}
          material={materials.nord_grass}
          position={[-2.542, -4.881, -0.105]}
          rotation={[0.271, -0.18, 2.312]}
          scale={0.833}
        />
        <mesh
          name="grass_obj_07015_0"
          geometry={nodes.grass_obj_07015_0.geometry}
          material={materials.nord_grass}
          position={[5.314, 1.274, -0.037]}
          rotation={[0.08, 0.308, 1.568]}
          scale={1.149}
        />
        <mesh
          name="grass_obj_07016_0"
          geometry={nodes.grass_obj_07016_0.geometry}
          material={materials.nord_grass}
          position={[1.69, 4.81, 0.005]}
          rotation={[-0.213, 0.052, -1.68]}
          scale={1.064}
        />
        <mesh
          name="soil_0"
          geometry={nodes.soil_0.geometry}
          material={materials.GRASS}
          scale={4.206}
        />
        <mesh
          name="walls_0"
          geometry={nodes.walls_0.geometry}
          material={materials.wall}
          scale={4.206}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/fort_island2.glb");
