/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/marsh.glb -o src/components/Marsh.jsx -r public -k 
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const animationsName = ["Idle Animation"];

export const Marsh = (props) => {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/models/marsh.glb");
  const { actions } = useAnimations(animations, group);

  useFrame(() => {
    animationsName.forEach((animation) => {
      const action = actions[animation];
      action.play();
    });
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="18b1829dd4bc4c5e8935df75b386e59dabccleanermaterialmergergle">
            <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Object_3">
                <group name="Object_12">
                  <group name="TimeframeMainGroup002">
                    <group name="Object_14">
                      <mesh
                        name="Plane_241_6_0"
                        geometry={nodes.Plane_241_6_0.geometry}
                        material={materials.Plane_241}
                      />
                    </group>
                  </group>
                </group>
                <group
                  name="Object_16"
                  position={[0.219, 0.875, -0.143]}
                  rotation={[2.435, -0.671, -3.033]}
                  scale={0.291}
                >
                  <group name="MorphMainGroup">
                    <mesh
                      name="Plane_222"
                      geometry={nodes.Plane_222.geometry}
                      material={materials.Plane_222}
                      morphTargetDictionary={
                        nodes.Plane_222.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Plane_222.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
                <group
                  name="Object_19"
                  position={[0.247, 2.071, 1.084]}
                  rotation={[3.016, -0.441, 0.048]}
                  scale={[0.795, 0.799, 0.755]}
                >
                  <group name="MorphMainGroup001">
                    <mesh
                      name="Plane_103"
                      geometry={nodes.Plane_103.geometry}
                      material={materials.Plane_103}
                      morphTargetDictionary={
                        nodes.Plane_103.morphTargetDictionary
                      }
                      morphTargetInfluences={
                        nodes.Plane_103.morphTargetInfluences
                      }
                    />
                  </group>
                </group>
                <group
                  name="Object_4"
                  position={[-0.123, 0.126, 0.001]}
                  scale={2.845}
                >
                  <group name="TimeframeMainGroup">
                    <group name="Object_6">
                      <mesh
                        name="Plane_243_2_0"
                        geometry={nodes.Plane_243_2_0.geometry}
                        material={materials.Plane_243}
                      />
                    </group>
                  </group>
                </group>
                <group name="Object_8">
                  <group name="TimeframeMainGroup001">
                    <group name="Object_10">
                      <mesh
                        name="Plane_242_4_0"
                        geometry={nodes.Plane_242_4_0.geometry}
                        material={materials.Plane_242}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/marsh.glb");
