/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/mountain.glb -o src/components/Mountain.jsx -r public -k 
*/

import React, { useRef } from "react";
import { useGLTF, Cloud } from "@react-three/drei";
import { useControls } from "leva";
export default function Mountain(props) {
  const { nodes, materials } = useGLTF("/models/mountain.glb");
  // const { posX, posY, posZ } = useControls({
  //   posX: {
  //     value: 0,
  //     min: -1000,
  //     max: 1000,
  //     step: 2,
  //   },
  //   posY: {
  //     value: 0,
  //     min: -1000,
  //     max: 1000,
  //     step: 2,
  //   },
  //   posZ: {
  //     value: 0,
  //     min: -1000,
  //     max: 1000,
  //     step: 2,
  //   },
  // scale: {
  //   value: 0.15,
  //   min: 0.001,
  //   max: 10,
  //   step: 0.005,
  // },
  // intensity: { min: 0, max: 10, value: 1, step: 0.5 },
  // x: { min: -100, max: 100, value: 0, step: 1 },
  // y: { min: -100, max: 100, value: -11, step: 1 },
  // z: { min: -100, max: 100, value: -30, step: 1 },
  // });

  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          name="Object_2"
          geometry={nodes.Object_2.geometry}
          material={materials["default"]}
          scale={0.1}
        />
      </group>
      <Cloud
        position={[30, 20, 20]}
        rotation={[0, 0, 0]}
        depthTest={false}
        speed={1}
        opacity={0.3}
      />
      <Cloud
        position={[30, 20, 10]}
        rotation={[0, 0, 0]}
        depthTest={false}
        speed={1}
        opacity={0.3}
      />
    </group>
  );
}

useGLTF.preload("/models/mountain.glb");
