/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/models/mountain.glb -o src/components/Mountain.jsx -r public -k 
*/

import { useGLTF } from "@react-three/drei";
import { useMemo } from "react";
import * as THREE from "three";

export default function Mountain({
  color,
  opacity = 1,
  roughness,
  metalness,
  ...props
}) {
  const { nodes, materials } = useGLTF("/models/mountain.glb");
  const mountainMaterial = useMemo(() => {
    const material = materials["default"].clone();

    if (color) {
      material.color.multiply(new THREE.Color(color));
    }
    if (roughness !== undefined) material.roughness = roughness;
    if (metalness !== undefined) material.metalness = metalness;

    material.opacity *= opacity;
    material.transparent = material.transparent || opacity < 1;

    return material;
  }, [color, materials, opacity, roughness, metalness]);

  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          name="Object_2"
          geometry={nodes.Object_2.geometry}
          material={mountainMaterial}
          scale={0.1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/mountain.glb");
