/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 plank.glb -o Plank.jsx 
*/

import React, { useEffect, useLayoutEffect, useMemo } from "react";
import { useGLTF } from "@react-three/drei";

// Dimensions of the centered, one-unit-wide sign variant below. Its broad
// wooden face lies in XY and faces +Z, so inscriptions can sit just in front.
export { SIGN_PLANK_HEIGHT, SIGN_PLANK_DEPTH, SIGN_PLANK_FACE_Z } from "./contactSignLayout";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/plank.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plank_Broken_HP_plank_broken_0.geometry}
        material={materials.plank_broken}
        position={[-10.231, -0.193, -2.245]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

export function SignPlank({
  color = "#795340",
  emissive = "#b5e74b",
  emissiveIntensity = 0,
  ...props
}) {
  const { nodes, materials } = useGLTF("/models/plank.glb");
  const geometry = useMemo(() => {
    // The source geometry already has its long axis along X and its broad
    // surface toward +Z; the authored scene rotation lays it flat on the floor.
    const normalized = nodes.Plank_Broken_HP_plank_broken_0.geometry.clone();
    normalized.computeBoundingBox();
    const width = normalized.boundingBox.max.x - normalized.boundingBox.min.x;
    normalized.center();
    normalized.scale(1 / width, 1 / width, 1 / width);
    normalized.computeBoundingBox();
    normalized.computeBoundingSphere();
    return normalized;
  }, [nodes]);
  const material = useMemo(() => {
    const wood = materials.plank_broken.clone();
    wood.roughness = 0.95;
    wood.metalness = 0;
    return wood;
  }, [materials]);

  useLayoutEffect(() => {
    material.color.set(color);
    material.emissive.set(emissive);
    material.emissiveIntensity = emissiveIntensity;
  }, [material, color, emissive, emissiveIntensity]);

  useEffect(() => () => geometry.dispose(), [geometry]);
  useEffect(() => () => material.dispose(), [material]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={geometry} material={material} castShadow receiveShadow />
    </group>
  );
}

useGLTF.preload("/models/plank.glb");
