/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scroll.glb -o Scroll.jsx 
*/

import { useEffect, useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Model({ normalized = false, topology = false, material, ...props }) {
  const { nodes, materials } = useGLTF("/models/scroll.glb");
  const geometry = nodes.Scroll_Scroll_0.geometry;
  const topologyGeometry = useMemo(() => {
    if (!topology) return null;
    const copy = geometry.index ? geometry.toNonIndexed() : geometry.clone();
    const barycentric = new Float32Array(copy.attributes.position.count * 3);
    const edgeMask = new Float32Array(barycentric.length).fill(1);
    const uv = copy.attributes.uv;
    for (let vertex = 0; vertex < copy.attributes.position.count; vertex++) {
      barycentric[vertex * 3 + vertex % 3] = 1;
    }
    // Preserve the model's quad strips without drawing their triangulation
    // diagonals. Irregular parts retain their original mesh edges.
    if (uv) for (let triangle = 0; triangle < uv.count; triangle += 3) {
      const gridEdges = [0, 1, 2].map((edge) => {
        const a = triangle + (edge + 1) % 3;
        const b = triangle + (edge + 2) % 3;
        return Math.abs(uv.getX(a) - uv.getX(b)) < 0.00001
          || Math.abs(uv.getY(a) - uv.getY(b)) < 0.00001;
      });
      if (gridEdges.filter(Boolean).length !== 2) continue;
      for (let vertex = 0; vertex < 3; vertex++) {
        edgeMask.set(gridEdges.map(Number), (triangle + vertex) * 3);
      }
    }
    copy.setAttribute("barycentric", new THREE.BufferAttribute(barycentric, 3));
    copy.setAttribute("edgeMask", new THREE.BufferAttribute(edgeMask, 3));
    return copy;
  }, [geometry, topology]);
  useEffect(() => () => topologyGeometry?.dispose(), [topologyGeometry]);
  // Optional unit length along X makes the supplied model easy to arrange in
  // the island exhibit while preserving its original generated transform.
  const unit = useMemo(() => {
    if (!geometry.boundingBox) geometry.computeBoundingBox();
    const center = geometry.boundingBox.getCenter(new THREE.Vector3());
    const size = geometry.boundingBox.getSize(new THREE.Vector3());
    const scale = 1 / size.x;
    return { scale, position: center.multiplyScalar(-scale).toArray() };
  }, [geometry]);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={topologyGeometry || geometry}
        material={material || materials.Scroll}
        position={normalized ? unit.position : [-0.003, 1.982, -0.019]}
        rotation={normalized ? [0, 0, 0] : [-Math.PI / 2, 0, 0]}
        scale={normalized ? unit.scale : 100}
        castShadow
        receiveShadow
      />
    </group>
  );
}

useGLTF.preload("/models/scroll.glb");
