/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 blue_whale_textured.glb -o Whale2.jsx 
Author: Bohdan Lvov (https://sketchfab.com/ostapblendercg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-whale-textured-d24d19021c724c3a9134eebcb76b0e0f
Title: Blue Whale - Textured
*/

import React from "react";
import { useGraph, useFrame } from "@react-three/fiber";
import {
  useGLTF,
  useAnimations,
  Text,
  RenderTexture,
  Decal,
  PerspectiveCamera,
} from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

const animationsName = ["Swimming"];

export default function Whale(props) {
  const group = React.useRef();
  const textRef = React.useRef();
  const { scene, animations } = useGLTF("/models/blue_whale.glb");

  // Deep clone the scene and its resources
  const clone = React.useMemo(() => {
    const clonedScene = SkeletonUtils.clone(scene);
    clonedScene.traverse((child) => {
      if (child.material) {
        child.material = child.material.clone();
      }
    });
    return clonedScene;
  }, [scene]);

  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useFrame(() => {
    animationsName.forEach((animation) => {
      const action = actions[animation];
      action.play();
    });
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={286.415}
        >
          <group name="WhaleAnim03fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="locator3"
                  position={[0, 0.343, 0.666]}
                  rotation={[0.035, 0, 0]}
                >
                  <group name="Object_7">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_36" />
                    <skinnedMesh
                      name="Object_37"
                      geometry={nodes.Object_37.geometry}
                      material={materials.lambert1}
                      skeleton={nodes.Object_37.skeleton}
                    />
                  </group>
                </group>
                <group name="pSphere2" position={[2.061, 0.381, 1.034]} />
                <group name="polySurface1" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/blue_whale_textured.glb");
